export {UserCard} from "./UserCard/UserCard.component.jsx"
export {UserList} from "./UserList/UserList.component.jsx"
export {PostCard} from "./PostCard/PostCard.component.jsx"
export {UserPosts} from "./UserPosts/UserPosts.component.jsx"
export {InputForm} from "./InputForm/InputForm.component.jsx"